### ISSUE TITLE
Feature request: gizmo size independent of distance from camera

### ISSUE THREAD

**Issue by onqtam** [ddiakopoulos/tinygizmo#4]
It would be useful to have an option (like the snapping ones) to get the gizmo scaled according to the distance from the camera so it remains with constant size on the screen no matter where it is in the world.

cool project! thanks for making it! It is a lot simpler than the 2 other immediate mode gizmos I was evaluating!

Also the readme should be updated - the snapping options are in ```gizmo_application_state``` and not in ```interaction_state```

**Comment by ddiakopoulos** [comment]
Glad you find it useful! I've pushed a branch with this feature hard-coded into the translation gizmo. If it behaves as you expect, I'll modularize the feature into the the app state as a flag and apply it to the other gizmos as well: https://github.com/ddiakopoulos/tinygizmo/tree/screenspace_scale

Ps. thanks for doctest, too. I use it in a few private projects :)

**Comment by onqtam** [comment]
the feature in the ```screenspace_scale``` branch works as expected!

**Comment by ddiakopoulos** [comment]
@onqtam I just pushed an update to master. You can now set the `screenspace_scale` value in `gizmo_application_state` to activate this mode (otherwise it's drawn in world-space like usual). This new setting is given in pixels, so a reasonable value might be anywhere from 60 to 120.
