### ISSUE TITLE
[feature request] gizmo usage events - start/stop

### ISSUE THREAD

**Issue by onqtam** [ddiakopoulos/tinygizmo#6]
perhaps by querying some flag of the state after updating the context - this would be very useful for easier undo/redo of actions and would also make it much easier to determine if the input is being consumed by the gizmo or not.

**Comment by ddiakopoulos** [comment]
Ha! I just prototype implemented this a few days ago for one of my projects. Similar to ImGui, the `tinygizmo::transform_gizmo` function now returns a bool. 

I had to fuss around with the behavior a bit, but it returns true if a gizmo is being _hovered_ or actively edited (click + drag). I won't have time to put it on a branch until later this week, but you can find my prototype here if you'd like to play around with it: https://github.com/ddiakopoulos/sandbox/blob/master/third_party/tiny-gizmo.cpp

For undo/redo, it might be as simple as using this new bool in conjunction with a method to check if the old transform is the new transform or not (just to disambiguate the hover state).

**Comment by onqtam** [comment]
quick note: ```inline bool operator != (const rigid_transform & a, const rigid_transform & b)``` - it compares only orientation and position but not scale

**Comment by onqtam** [comment]
currently if I display the gizmo, but dont hover it, and then I click somewhere far from it and set ```state.mouse_left``` to ```true``` (so not using it) - ```tinygizmo::transform_gizmo``` starts returning true - I think this is a bug.

Aside from this - I think returning true/false about hovering it should be enough for all my needs :)

**Comment by ddiakopoulos** [comment]
Sorry for taking so long on this. I fixed up the inequality operator and figured out the one or two edge-cases where hovering isn't enough to determine the state (i.e. dragging the gizmo but the cursor isn't hovering the geometry). I've pushed these changes to master, so please try it out when you get a chance!

**Comment by onqtam** [comment]
it will be perhaps in 10 days after [my cppcon talk](https://cppcon2017.sched.com/event/BgsI/mix-tests-and-production-code-with-doctest-implementing-and-using-the-fastest-modern-c-testing-framework) :D

**Comment by onqtam** [comment]
seems to work fine - thanks!
